package utils

import "fmt"

// SSLConfig holds configuration for SSL setup
type SSLConfig struct {
	Domain    string
	Email     string
	ServerIP  string
	ConfigDir string // Directory where app config files are stored
}

// GetCertManagerCommand returns the command to run cert-manager setup
func GetCertManagerCommand(email, domain, scriptsDir string) string {
	return fmt.Sprintf(`cd %s && echo -e "%s\n%s" | bash certmanager.sh`,
		scriptsDir, email, domain)
}

// GetSSLConfigYAML returns the SSL configuration to append to vars.yaml
func GetSSLConfigYAML() string {
	return `
# SSL Configuration - Auto-generated by selfhost-installer
ingress-nginx: &ingress-nginx
  controller:
    config:
      ssl-redirect: true
      force-ssl-redirect: true
`
}

// GetAppendSSLConfigCommand returns command to append SSL config to vars.yaml
func GetAppendSSLConfigCommand(configFile string) string {
	sslConfig := GetSSLConfigYAML()
	return fmt.Sprintf("cat >> %s << 'EOF'\n%s\nEOF", configFile, sslConfig)
}

// GetDirectCertManagerSetup returns commands to setup cert-manager directly using kubectl
// This bypasses the OpenReplay cert-manager script which has DNS validation issues
func GetDirectCertManagerSetup(email, domain string) []string {
	issuerYAML := fmt.Sprintf(`apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: %s
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx`, email)

	certificateYAML := fmt.Sprintf(`apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: %s-tls
  namespace: app
spec:
  secretName: %s-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - %s`, domain, domain, domain)

	return []string{
		// Install cert-manager if not already installed
		"kubectl get namespace cert-manager >/dev/null 2>&1 || kubectl create namespace cert-manager",
		"kubectl get deployment -n cert-manager cert-manager >/dev/null 2>&1 || kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml",

		// Wait for cert-manager to be ready
		"sleep 30",
		"kubectl wait --for=condition=ready pod -l app=cert-manager -n cert-manager --timeout=300s",

		// Create ClusterIssuer
		fmt.Sprintf("cat <<'EOF' | kubectl apply -f -\n%s\nEOF", issuerYAML),

		// Create Certificate
		fmt.Sprintf("cat <<'EOF' | kubectl apply -f -\n%s\nEOF", certificateYAML),

		// Wait a bit for cert to be requested
		"sleep 10",
	}
}
